services:
  - type: web
    name: cyber-snake
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
  - type: static
    name: cyber-snake-static
    buildCommand: null
    publishDir: .  # Root directory
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
